name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'
          channel: 'stable'
      - run: flutter pub get
      - run: dart format lib/
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings

  test:
    name: Test
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test

#  build-android:
#    name: Build Android APK
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.29.x'
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter build apk --debug
#      - uses: actions/upload-artifact@v4
#        with:
#          name: android-apk
#          path: build/app/outputs/flutter-apk/*.apk
#
#  build-ios:
#    name: Build iOS IPA
#    needs: test
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.29.x'
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter build ios --debug --no-codesign
